.travis.yml
build.gradle
src/main/kotlin/com/vanniktech/dependency/graph/generator/DependencyGraphGeneratorExtension.kt
src/main/kotlin/com/vanniktech/dependency/graph/generator/DotGenerator.kt
src/test/java/com/vanniktech/dependency/graph/generator/DotGeneratorTest.kt

Fixes #7
Now everything will be included by default and if wanted one can provide a custom Generator to filter for instance for only one flavor.

Support Android flavors and buildTypes out of the box and add include Configuration extension point to Generator.

---

README.md
src/main/kotlin/com/vanniktech/dependency/graph/generator/DependencyGraphGeneratorTask.kt

Added instructions for installing Graphviz via Windows, and clarifying that the Mac instructions requires Homebrew to be installed

Adding Windows support

---

README.md

Addresses #20, which is now a "won't fix" because the minimum required version is now documented to be 4.0.

Adding minimum Gradle version to Readme

---

src/main/kotlin/com/vanniktech/dependency/graph/generator/DotGenerator.kt

Use identifier for detecting duplicate connections instead of the ResolvedDependency.

---

src/main/kotlin/com/vanniktech/dependency/graph/generator/DotGenerator.kt
src/test/java/com/vanniktech/dependency/graph/generator/DotGeneratorTest.kt

Handle recursive depenencies correctly.

---

build.gradle
src/main/kotlin/com/vanniktech/dependency/graph/generator/DependencyGraphGeneratorExtension.kt
src/main/kotlin/com/vanniktech/dependency/graph/generator/DependencyGraphGeneratorPlugin.kt
src/main/kotlin/com/vanniktech/dependency/graph/generator/DependencyGraphGeneratorTask.kt
src/test/java/com/vanniktech/dependency/graph/generator/DependencyGraphGeneratorExtensionTest.kt
src/test/java/com/vanniktech/dependency/graph/generator/DependencyGraphGeneratorPluginTest.kt
src/test/java/com/vanniktech/dependency/graph/generator/GeneratorTest.kt

Generator: Allow custom output formats.

---

build.gradle

Related issue: https://github.com/vanniktech/gradle-dependency-graph-generator-plugin/issues/58.

Update graphviz-java version to 0.5.3

---

src/main/kotlin/com/vanniktech/dependency/graph/generator/DependencyGraphGeneratorPlugin.kt
src/main/kotlin/com/vanniktech/dependency/graph/generator/DependencyGraphGeneratorTask.kt
src/main/kotlin/com/vanniktech/dependency/graph/generator/ProjectDependencyGraphGeneratorTask.kt
src/test/java/com/vanniktech/dependency/graph/generator/DependencyGraphGeneratorPluginTest.kt

Remove the project build.gradle file as an input

---

src/main/kotlin/com/vanniktech/dependency/graph/generator/DependencyGraphGeneratorExtension.kt
src/main/kotlin/com/vanniktech/dependency/graph/generator/DependencyGraphGeneratorTask.kt
src/main/kotlin/com/vanniktech/dependency/graph/generator/ProjectDependencyGraphGeneratorTask.kt
src/test/java/com/vanniktech/dependency/graph/generator/DependencyGraphGeneratorPluginTest.kt

was seeing the multi project test fail due to missing PNG outputs, though I don't see how the default `ALL` could be getting initiated with only SVG as the format.
all the graphviz types not being serializable leads to some less than ideal conversion for the input values. 
but this should at least ensure the tasks are marked as dirty when any value that feeds into them changes.
my least favorite element is the `@get:Input val dotFormatGraph` since it ends up running the bulk of the logic to generate it, but was the simplest way to cover all the inputs from the gradle model without completely restructuring the generator logic.
closes #95

mark task inputs as such.

---

src/main/kotlin/com/vanniktech/dependency/graph/generator/DependencyGraphGeneratorExtension.kt
src/main/kotlin/com/vanniktech/dependency/graph/generator/DependencyGraphGeneratorTask.kt
src/main/kotlin/com/vanniktech/dependency/graph/generator/ProjectDependencyGraphGeneratorTask.kt

Mark all task properties that should not be considered during up-to-date checks as @Internal. Required by Gradle 7.0 onwards.
Fixes #121

Gradle 7.0 compatibility

---

src/main/kotlin/com/vanniktech/dependency/graph/generator/ProjectDependencyGraphGenerator.kt
src/main/kotlin/com/vanniktech/dependency/graph/generator/extensions.kt
src/test/java/com/vanniktech/dependency/graph/generator/DependencyGraphGeneratorPluginTest.kt

In monorepo, generateProjectDependencyGraph from individual sub project would be more practical. 
eg. `./gradlew app:generateProjectDependencyGraph`

Support generateProjectDependencyGraph in SubProject

---

CHANGELOG.md
README.md
gradle.properties

Hereby the changes to get the version 0.7.0 released as discussed at https://github.com/vanniktech/gradle-dependency-graph-generator-plugin/issues/127#issuecomment-996984259

Prepare version 0.7.0

---

README.md

The documentation doesn't mention the path of the output report for the dependency graph which is hard to find. I've added it now so someone else doesn't have to trip to google & issues to see where it will be generated. 
Relates to #147 #139

[Documentation] Mention output file path in documentation

---

src/main/kotlin/com/vanniktech/dependency/graph/generator/DependencyGraphGeneratorTask.kt
src/main/kotlin/com/vanniktech/dependency/graph/generator/ProjectDependencyGraphGeneratorTask.kt
src/test/java/com/vanniktech/dependency/graph/generator/DependencyGraphGeneratorPluginTest.kt

Fixes #155
Here is what it looks like on Windows:
```
> Task :generateDependencyGraph
C:\...\build\reports\dependency-graph\dependency-graph.dot
C:\...\build\reports\dependency-graph\dependency-graph.png
C:\...\build\reports\dependency-graph\dependency-graph.svg
BUILD SUCCESSFUL in 27s
```
Unfortunately, clickable file uri in IntelliJ's terminal is awful.
On Windows, it works only if the IDE has indexed the file before printing it.
Not sure about the Unix/Macos behavior.

Log output files path: dot, png, svg

---

src/main/kotlin/com/vanniktech/dependency/graph/generator/DependencyGraphGenerator.kt
src/main/kotlin/com/vanniktech/dependency/graph/generator/ProjectDependencyGraphGenerator.kt
src/test/java/com/vanniktech/dependency/graph/generator/DependencyGraphGeneratorPluginTest.kt
src/test/java/com/vanniktech/dependency/graph/generator/DependencyGraphGeneratorTest.kt

The https://github.com/nidi3/graphviz-java dependency overrides the default Graphviz dpi value to 72.
See #158 and https://github.com/nidi3/graphviz-java/issues/233 for more details.
Closes #158

Force the dpi value to 100

---

src/main/kotlin/com/vanniktech/dependency/graph/generator/ProjectDependencyGraphGenerator.kt

Closes nidi3/graphviz-java#234
Closes vanniktech/gradle-dependency-graph-generator-plugin#167
Not sure if this is an issue on the nidi3/graphviz-java repository. But there is no direct function to access declared nodes, meaning nodes without links (not edges).

Project Graph: Add dependencies from the root (declaration) nodes only

---

README.md

Applying the plugin on the root project my not be desirable.
And most projects will already apply this on the root project, so it's less confusing (and matches the groovy snippet)

Remove `rootProject` from Kotlin snippet

---

src/main/kotlin/com/vanniktech/dependency/graph/generator/DependencyGraphGeneratorTask.kt
src/main/kotlin/com/vanniktech/dependency/graph/generator/ProjectDependencyGraphGeneratorTask.kt

If we specified
````kotlin
outputFormats = listOf(DOT)
````
The .dot file would be printed twice.

Print distinct files

---

src/main/kotlin/com/vanniktech/dependency/graph/generator/DependencyGraphGeneratorExtension.kt
src/main/kotlin/com/vanniktech/dependency/graph/generator/DependencyGraphGeneratorTask.kt
src/main/kotlin/com/vanniktech/dependency/graph/generator/ProjectDependencyGraphGeneratorTask.kt

On big projects, we need to update Graphviz's `totalMemory`, otherwise we get an error.
This would allow us to configure Graphviz's internals:
```kotlin
graphviz = { it.totalMemory( /*...*/ ) }
```

Expose Graphviz instance

---

src/main/kotlin/com/vanniktech/dependency/graph/generator/ProjectDependencyGraphGenerator.kt
src/test/java/com/vanniktech/dependency/graph/generator/ProjectDependencyGraphGeneratorIncludeProjectTest.kt

When filtering out projects with `ProjectGenerator.includeProject`, the process will throw a `NoSuchElementException("Collection contains no element matching the predicate.")` because the destination project has been filtered out of the root nodes.
I'm making it as a draft because I'd like to create a test for it (there might be the same issue as well for the `DependencyGraphGenerator`).
The regression was introduced in https://github.com/vanniktech/gradle-dependency-graph-generator-plugin/commit/8f7c8296b704d84dde35a0d92b22f4b5d66a5a9b.

Fix destination project might not be included

---

src/main/kotlin/com/vanniktech/dependency/graph/generator/ProjectTarget.kt

Update Kotlin Multiplatform `ProjectTarget` color to improve color contrast accessibility. New color is based on Kotlin brand assets resources `#7F52FF` with lightness applied `#A280FF`.
-----
-----

Update Kotlin Multiplatform ProjectTarget color to improve color contrast accessibility

---

.gitignore
src/main/kotlin/com/vanniktech/dependency/graph/generator/ProjectDependencyGraphGenerator.kt

Honestly I'm not sure exactly what causes my issue, but when I bumped my project up from Gradle 8.9 to 8.10 I started getting duplicated links in my project dependency tree. So it would generate a dotfile something like:
```dot
digraph {
...
":a"
":b"
":c"
":d"
":a" -> ":b"
":a" -> ":b"
":a" -> ":b"
":a" -> ":c"
":a" -> ":c"
":b" -> ":d"
}
```
when before it would only have one instance of each module link. The duplication would happen at seemingly random frequencies, but it was repeatable for the same module links.
This PR squashes the issue by forcing uniqueness of the pair of "from" and "to" nodes on the `ProjectDependencyContainer` class. All tests pass okay and the dotfile comes out okay on my machine, but I'd be interested to see whether anyone else sees something similar.
Also …

Fix duplicated tree links in Gradle 8.10
